#!/bin/bash
#
# This script is a wrapper around (and in its full version an extension of)
# ximera's xake command THAT ENSURES IT'S RUNNING IN A DOCKER CONTAINER
#
# Usage:
#   xmlatex bake
#   xmlatex bake test/myximerafile.tex
#   xmlatex bash
#   xmlatex frost
#   xmlatex serve
#   xmlatex name
#   xmlatex all
#
# Advanced usage:
#   XAKE_IMAGE=ghcr.io/ximeraproject/xake2023:latest xmlatex compile demo.tex
#   COMMAND=pdflatex xmlatex demo.tex
#
# Debugging:
#   DEBUG=1 xmlatex bake ...
#

: "${CONFIG_FILE:=./xmScripts/config.txt}"

if [[ -f "$CONFIG_FILE" ]]
then
    [[ -n "$DEBUG" ]] && echo "Loading settings from config file $CONFIG_FILE."
    # shellcheck disable=SC1090
    . "$CONFIG_FILE"
fi


# ------------------------------------------------------------
# Defaults
# ------------------------------------------------------------

: "${XAKE_BASE:=ximeralatex}"
: "${XAKE_VERSION:=v2.7.10}"
: "${XAKE_CONTAINER:=$XAKE_BASE:$XAKE_VERSION}"
: "${DOCKER_REPO:=ghcr.io/ximeraproject/}"

# Historic compatibility
: "${XAKE_IMAGE:=$DOCKER_REPO$XAKE_CONTAINER}"
: "${DOCKER_IMAGE:=$XAKE_IMAGE}"

: "${DOCKER_DEFAULT_PLATFORM:=linux/amd64}"
export DOCKER_DEFAULT_PLATFORM

: "${SERVER_PORT:=2000}"
: "${SERVER_NAME:=ximeraserver}"
: "${SERVER_IMAGE:=registry.gitlab.kuleuven.be/wet/ximera/ximeradocker:2.3_b}"

# Dev environment
: "${DEVENV_TGZFILE:=xmDevEnvFiles.tgz}"
: "${DEVENV_VERSION:=releases/latest/download}"
: "${DEVENV_REPO:=ximeraProject/ximeraNewProject}"
: "${DEVENV_URL:=https://github.com/$DEVENV_REPO/$DEVENV_VERSION/xmDevEnvFiles.tgz}"


# ------------------------------------------------------------
# Project mount and command
# ------------------------------------------------------------

: "${MOUNTDIR:=$(pwd)}"
: "${XM_KEYFILE:=.xmKeyFile}"
: "${COMMAND:=xmlatex}"


# ------------------------------------------------------------
# Detect whether we are already inside a container
# ------------------------------------------------------------

if [[ -f /.dockerenv ]]
then
    [[ -n "$DEBUG" ]] && \
        echo "Running in docker container (with local hostname $HOSTNAME)"

elif [[ -n "$KUBERNETES_SERVICE_HOST" ]]
then
    echo "Running in kubernetes container ($KUBERNETES_SERVICE_HOST)"

else
    [[ -n "$DEBUG" ]] && echo "Running $0 on host ($HOSTNAME)"


    # --------------------------------------------------------
    # Interactive mode
    # --------------------------------------------------------

    INTERACTIVE=""

    if [[ "${1:-}" == "-i" ]]
    then
        INTERACTIVE="-it"
        shift
    fi

    if [[ "${1:-}" == "bash" ]]
    then
        INTERACTIVE="-it"
    fi

    if tty >/dev/null 2>&1
    then
        INTERACTIVE="-it"
    fi


    # --------------------------------------------------------
    # Local IP
    # --------------------------------------------------------

    if [[ -z "${LOCAL_IP:-}" ]]
    then
        LOCAL_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
        [[ -n "$DEBUG" ]] && echo "Setting LOCAL_IP=$LOCAL_IP"
    fi


    # --------------------------------------------------------
    # Ximera server
    # --------------------------------------------------------

    if [[ "${1:-}" == "ximeraserver" ]]
    then
        echo "Starting ximera $SERVER_NAME from $SERVER_IMAGE on port $SERVER_PORT"

        docker run \
            --rm \
            --name "$SERVER_NAME" \
            -p "2000:$SERVER_PORT" \
            "$SERVER_IMAGE"

        exit $?
    fi


    # --------------------------------------------------------
    # Convert WSL path to Windows path for Docker Desktop
    # --------------------------------------------------------

    DOCKER_MOUNTDIR="$MOUNTDIR"

    if grep -qi microsoft /proc/version 2>/dev/null \
        && command -v wslpath >/dev/null 2>&1
    then
        DOCKER_MOUNTDIR="$(wslpath -w "$MOUNTDIR")"
    fi


    # --------------------------------------------------------
    # Run container using the current WSL user
    # --------------------------------------------------------



    echo "Restarting myself in docker (from image $DOCKER_IMAGE)"

    if [[ -n "$DEBUG" ]]
    then
        echo "Dockerinstellingen:"
        echo "  projectmap : $MOUNTDIR"
        echo "  dockerpad  : $DOCKER_MOUNTDIR"
        echo "  mountpunt  : /code"
        echo "  image      : $DOCKER_IMAGE"
        echo "  commando   : $COMMAND $*"
    fi


docker run \
  --env LOCAL_IP \
  --env XIMERA_URL \
  --env XIMERA_NAME \
  --env GPG_KEY \
  --env GPG_KEY_ID \
  --env DEBUG \
  --network host \
  --rm \
  $INTERACTIVE \
  --mount "type=bind,source=${DOCKER_MOUNTDIR},target=/code" \
  "$DOCKER_IMAGE" \
  "$COMMAND" \
  "$@"

    exit $?
fi


# ------------------------------------------------------------
# This limited wrapper should not run inside the container
# ------------------------------------------------------------

echo "Sorry, this limited version of this xmlatex script should not be run inside a docker container."
echo "Find and run the full version, perhaps called xmlatex.full."

exit 1